name: Build and Deploy Script

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Adding Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20
        
    - name: Install Dependencies
      run: |
        cd tictactoe
        npm install

    - name: Build Angular App
      run: | 
        cd tictactoe
        npm run build

    - name: Deploy to gh pages
      run: |
        cd tictactoe
        npx angular-cli-ghpages --dir=dist/tictactoe
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
